name: Example Action
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get changed files
      run: |
        git diff-tree --no-commit-id --name-only -r HEAD HEAD~1 > changed_files.txt
    - name: Do something with changed files
      run: |
        while read filename; do
          echo "Processing $filename"
          # Do something with $filename
        done < changed_files.txt

