name: Update Header
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#     - name: Get changed files
#       id: changed-files-specific
#       uses: tj-actions/changed-files@v35

#       with:
#         since_last_remote_commit: true
        
#         files: |
#           *.java
#     #       !*.md
#     #       test_directory
#     #       **/*.sql


        
        
    - name: Setting up the git user
      run: |
          git config --global user.name 'Muhammad Khuzaima Umair'
          git config --global user.email 'mkhuzaima@users.noreply.github.com'
          

    - name: printing sha
      run: |
        CURRENT=${GITHUB_SHA}
        PREVIOUS=${{ github.event.before }}
        
        echo $CURRENT
        echo $PREVIOUS

    - name: all changed files
      run: |
        git diff --diff-filter=AM --name-only ${{github.event.before}}..${GITHUB_SHA}
        git diff --diff-filter=AM --name-only HEAD~3..HEAD~1
          
    - name: Get changed java files
      run: |
        echo 'before loop'
        for file in $(git diff --diff-filter=AM --name-only HEAD~~..HEAD *.java ) ; do
          echo "$file was changed"
          # python ./.github/workflows/updateHeader.py $file
          python updateHeader.py $file

          # create commit 
          git commit -am "Formatted $file"
        done
        
        
        git push || echo "There is nothing to push"
