name: Update Header
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v35

#       with:
#         since_last_remote_commit: true
        
#         files: |
#           *.java
#     #       !*.md
#     #       test_directory
#     #       **/*.sql


    
    - name: Run for all changed files
      run: |
        echo ${GITHUB_WORKSPACE}
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
          # python ./.github/workflows/updateHeader.py $file
          python updateHeader.py $file
        done
        
        
    - name: Setting up the git user
      run: |
          git config --global user.name 'Muhammad Khuzaima Umair'
          git config --global user.email 'mkhuzaima@users.noreply.github.com'
          
          
    - name: printing sha
      run: |
        CURRENT=${GITHUB_SHA}
        PREVIOUS=${{ github.event.before }}
        
        echo $CURRENT
        echo $PREVIOUS

    - name: all changed files
      run: |
        git diff --diff-filter=AM --name-only ${{github.event.before}}..${GITHUB_SHA}
          
    - name: Get changed java files
      run: |
        $(git diff --diff-filter=AM --name-only ${{ github.event.before }}..${GITHUB_SHA} *.java
        echo 'before loop'
        for file in $(git diff --diff-filter=AM --name-only ${{ github.event.before }}..${GITHUB_SHA} *.java ) ; do
          echo "$file was changed"
          # python ./.github/workflows/updateHeader.py $file
          python updateHeader.py $file

          # create commit 
          git commit -am "Formatted $file"
        done
        
        
        git push || echo "There is nothing to push"

    
    



    
#     - name: Run for changed java files
#       run: |
#         # cat .github/workflows/updateHeader.py
#         for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
#           echo "$file was changed"
#           python .github/workflows/updateHeader.py $file
#           # python ./.github/workflows/updateHeader.py $file

#           # create commit 
#           git commit -am "Formatted $file"

#         done
#         git push || echo "There is nothing to push"

#         git config --global user.name 'Your Name'
#         git config --global user.email 'your-username@users.noreply.github.com'
          
    # - name: Run step if only the files listed above change
    #   if: steps.changed-files-specific.outputs.only_changed == 'true'
    #   run: |
    #     echo "Only files listed above have changed."

    # - name: Run step if any of the listed files above is deleted
    #   if: steps.changed-files-specific.outputs.any_deleted == 'true'
    #   run: |
    #     for file in ${{ steps.changed-files-specific.outputs.deleted_files }}; do
    #       echo "$file was deleted"
    #     done

    # - name: Run step if all listed files above have been deleted
    #   if: steps.changed-files-specific.outputs.only_deleted == 'true'
    #   run: |
    #     for file in ${{ steps.changed-files-specific.outputs.deleted_files }}; do
    #       echo "$file was deleted"
    #     done
